# -*- coding: utf-8 -*-
"""Eletrical_Insghts_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDY2PVZCTrJPd0ZTyWz3k13Lhdn8Nm5a
"""

###Inserindo bibliotecas e lendo as planilhas que serão utilizadas
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

excel_file = pd.ExcelFile(r'/content/Planilha_Anomalias_Eletricas_Preenchida.xlsx')
sheet_names = excel_file.sheet_names
print("Available sheet names", sheet_names)

###Limpando e analizando as planilhas
df_sobrecarga = pd.read_excel(excel_file, sheet_name='Sobrecarga')
df_sobrecarga = df_sobrecarga.dropna()

df_status = df_sobrecarga['Status']
df_status = df_status.value_counts()
df_sobrecarga['Requer_Atencao'] = df_sobrecarga['Status'].isin(['ATENÇÃO', 'CRÍTICO'])

###Analisando casos de sobrecarga com matplotlib e criando PDF
with PdfPages("relatorio_tecnico.pdf") as pdf:
  # Pagina de Titulo
  fig_title = plt.figure(figsize=(8,11))
  plt.text(
      0.5,
      0.7,
      "Relatório Técnico de Anomalias Elétricas",
      fontsize=24,
      ha='center'
  )
  plt.text(
      0.5,
      0.55,
      "Sistema Automatizado de Monitoramento",
      fontsize=16,
      ha='center'
  )
  plt.text(
      0.5,
      0.4,
      "Desenvolvido em Python",
      fontsize=12,
      ha='center'
  )
  plt.axis('off')
  pdf.savefig(fig_title)
  plt.close(fig_title)

  # Pafina de Conclusão
  total = len(df_sobrecarga)
  criticos_count = len(df_sobrecarga[df_sobrecarga["Status"] == "CRÍTICO"])
  atencao = len(df_sobrecarga[df_sobrecarga["Status"] == "ATENÇÃO"])
  normal = len(df_sobrecarga[df_sobrecarga["Status"] == "NORMAL"])

  fig_summary = plt.figure(figsize=(8,11))
  texto = f"""
RESUMO TÉCNICO

Total de Equipamentos: {total}

Equipamentos Críticos: {criticos_count}

Equipamentos em Atenção: {atencao}

Equipamentos Normais: {normal}
"""
  conclusao = """
CONCLUSÃO

Foram identificadas anomalias elétricas em equipamentos
operando acima dos limites recomendados.

Recomenda-se inspeção técnica preventiva nos sistemas
classificados como críticos.

A seguir os graficos analisados
"""

  plt.text(0.1, 0.5, conclusao, fontsize=14, va='top')
  plt.text(0.4, 0.9, texto, fontsize=16, va='top')
  plt.axis('off')
  pdf.savefig(fig_summary)
  plt.close(fig_summary)

  #Estado dos equipamentos
  fig1 = plt.figure(figsize=(8, 6))
  plt.bar(df_status.index, df_status.values)
  plt.xlabel('Status')
  plt.ylabel('Quantidade')
  plt.title('Estado dos Equipamentos')
  pdf.savefig(fig1)
  plt.close(fig1)

  #Porcetargem dos equipamentos que necessitam atenção
  fig2 = plt.figure(figsize=(8, 6))
  plt.pie(df_status.values, labels=df_status.index, autopct='%1.1f%%')
  plt.title('Porcertagem dos equipamentos que exigem atenção')
  pdf.savefig(fig2)
  plt.close(fig2)

  #Comparação de corrente nominal e medida
  equipamentos = df_sobrecarga["Equipamento"]
  corrente_nominal = df_sobrecarga["Corrente Nominal (A)"]
  corrente_medida = df_sobrecarga["Corrente Medida (A)"]
  x = range(len(equipamentos))
  largura = 0.35
  fig3 = plt.figure(figsize=(8,6))
  plt.bar([i - largura/2 for i in x], corrente_nominal, width=largura, label="Nominal")
  plt.bar([i + largura/2 for i in x], corrente_medida, width=largura, label="Medida")
  plt.title("Corrente Nominal vs Corrente Medida")
  plt.xlabel("Equipamentos")
  plt.ylabel("Corrente (A)")
  plt.xticks(x, equipamentos, rotation=90, ha='right')
  plt.legend()
  plt.tight_layout()
  pdf.savefig(fig3)
  plt.close(fig3)

  #potencia por equipamento
  fig4 = plt.figure(figsize=(8, 6))
  plt.barh(df_sobrecarga["Equipamento"], df_sobrecarga["Potência (W)"], color='lightcoral')
  plt.title("Potência dos Equipamentos")
  plt.xlabel("Potência (W)")
  plt.ylabel("Equipamentos")
  plt.xticks(rotation=0)
  plt.yticks(rotation=0, ha='right')
  plt.tight_layout()
  pdf.savefig(fig4)
  plt.close(fig4)

  #Porcentual de sobrecarga por equipamento
  fig5 = plt.figure(figsize=(8, 6))
  colors = ['green' if x < 0 else 'red' for x in df_sobrecarga["Percentual de Sobrecarga (%)"]]
  plt.barh(df_sobrecarga["Equipamento"], df_sobrecarga["Percentual de Sobrecarga (%)"], color=colors)
  plt.title("Porcentagem de Sobrecarga por Equipamento")
  plt.xlabel("Porcentagem de Sobrecarga (%)")
  plt.ylabel("Equipamentos")
  plt.xticks(rotation=0)
  plt.yticks(rotation=0, ha='right')
  plt.tight_layout()
  pdf.savefig(fig5)
  plt.close(fig5)

  # Tabela analisada
  fig_table = plt.figure(figsize=(11, 8))
  ax = fig_table.add_subplot(111)
  ax.axis('off')
  table = ax.table(cellText=df_sobrecarga.values, colLabels=df_sobrecarga.columns, loc='center')
  table.auto_set_font_size(False)
  table.set_fontsize(8)
  table.auto_set_column_width(col=list(range(len(df_sobrecarga.columns))))
  ax.set_title('Tabela de Dados de Sobrecarga', fontsize=16)
  pdf.savefig(fig_table)
  plt.close(fig_table)

print("Dashboard PDF 'relatorio_tecnico.pdf' criado com sucesso!")
